AWSTemplateFormatVersion: '2010-09-09'
Description: A CloudFormation template for creating an S3 Bucket with an SNS Trigger.

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 f Bucket to create


Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: BucketOwnerFullControl
      LoggingConfiguration:
        DestinationBucketName: !Ref AccessLogBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
  AccessLogBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      VersioningConfiguration:
        Status: Enabled
